# Generated by Django 6.0.2 on 2026-02-25 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_brand_name_d23c0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=50)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('brief_received', 'Brief Received'), ('ideation', 'Ideation'), ('designing', 'Designing'), ('internal_review', 'Internal Review'), ('client_review', 'Client Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('published', 'Published')], default='brief_received', max_length=50)),
                ('given_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.brand')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_tasks', to=settings.AUTH_USER_MODEL)),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='api.task')),
            ],
            options={
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['brand'], name='api_task_brand_i_5cbf40_idx'), models.Index(fields=['status'], name='api_task_status_2aef03_idx'), models.Index(fields=['designer'], name='api_task_designe_3f008b_idx'), models.Index(fields=['given_at'], name='api_task_given_a_53ba26_idx'), models.Index(fields=['revision_of'], name='api_task_revisio_ccc647_idx')],
                'constraints': [models.UniqueConstraint(fields=('brand', 'task_number'), name='uniq_task_number_per_brand')],
            },
        ),
    ]
