# Generated by Django 6.0.2 on 2026-02-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='uniq_task_number_per_brand',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
    ]
