# Generated by Django 6.0.3 on 2026-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_revision_no_task_api_task_revisio_f203c8_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('designated_person', models.CharField(max_length=255)),
                ('client_interface', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_client_name_6d373d_idx'), models.Index(fields=['brand_name'], name='api_client_brand_n_25e2c0_idx'), models.Index(fields=['designated_person'], name='api_client_designa_cde923_idx')],
            },
        ),
    ]
