# Generated by Django 6.0.3 on 2026-03-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Digital Marketing Scope of Work', max_length=255)),
                ('social_media_platforms', models.JSONField(blank=True, default=list)),
                ('social_media_deliverables', models.JSONField(blank=True, default=list)),
                ('social_media_frequency', models.CharField(blank=True, max_length=255)),
                ('content_creation_items', models.JSONField(blank=True, default=list)),
                ('performance_marketing_platforms', models.JSONField(blank=True, default=list)),
                ('performance_marketing_deliverables', models.JSONField(blank=True, default=list)),
                ('performance_marketing_reporting', models.JSONField(blank=True, default=list)),
                ('seo_on_page', models.JSONField(blank=True, default=list)),
                ('seo_technical', models.JSONField(blank=True, default=list)),
                ('seo_off_page', models.JSONField(blank=True, default=list)),
                ('seo_reporting', models.JSONField(blank=True, default=list)),
                ('website_management_items', models.JSONField(blank=True, default=list)),
                ('branding_creative_support_items', models.JSONField(blank=True, default=list)),
                ('influencer_marketing_items', models.JSONField(blank=True, default=list)),
                ('email_marketing_items', models.JSONField(blank=True, default=list)),
                ('analytics_reporting_items', models.JSONField(blank=True, default=list)),
                ('strategy_consulting_items', models.JSONField(blank=True, default=list)),
                ('additional_services_items', models.JSONField(blank=True, default=list)),
                ('final_deliverables_summary', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_of_work_items', to='api.client')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['title'], name='api_scopeof_title_73b5d5_idx'), models.Index(fields=['created_at'], name='api_scopeof_created_7ae498_idx')],
            },
        ),
    ]
