# Generated by Django 6.0.3 on 2026-03-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scopeofwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeOfWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=100)),
                ('scope_area', models.CharField(max_length=150)),
                ('deliverables', models.TextField()),
                ('platforms', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_of_work_rows', to='api.client')),
                ('scope_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.scopeofwork')),
            ],
            options={
                'ordering': ['service_category', 'scope_area'],
                'indexes': [models.Index(fields=['service_category'], name='api_scopeof_service_090f7a_idx'), models.Index(fields=['scope_area'], name='api_scopeof_scope_a_5a33d3_idx'), models.Index(fields=['frequency'], name='api_scopeof_frequen_b91dd3_idx')],
            },
        ),
    ]
