# Generated by Django 6.0.3 on 2026-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scopeofworkitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scopeofworkitem',
            name='api_scopeof_frequen_b91dd3_idx',
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='delivered_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='planned_qty_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='task',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='scopeofworkitem',
            index=models.Index(fields=['status'], name='api_scopeof_status_f57f5d_idx'),
        ),
        migrations.RemoveField(
            model_name='scopeofworkitem',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='scopeofworkitem',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='scopeofworkitem',
            name='platforms',
        ),
    ]
