# Generated by Django 6.0.3 on 2026-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_scopeofworkitem_api_scopeof_frequen_b91dd3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120)),
                ('task', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('deliverable_type', models.CharField(max_length=100)),
                ('monthly_limit', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('tracking_method', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service', 'task'],
            },
        ),
        migrations.RemoveIndex(
            model_name='scopeofwork',
            name='api_scopeof_title_73b5d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='scopeofwork',
            name='api_scopeof_created_7ae498_idx',
        ),
        migrations.RemoveIndex(
            model_name='scopeofworkitem',
            name='api_scopeof_service_090f7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='scopeofworkitem',
            name='api_scopeof_scope_a_5a33d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='scopeofworkitem',
            name='api_scopeof_status_f57f5d_idx',
        ),
        migrations.AddIndex(
            model_name='servicetaskdefinition',
            index=models.Index(fields=['service'], name='api_service_service_e177a2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetaskdefinition',
            index=models.Index(fields=['task'], name='api_service_task_3324ee_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetaskdefinition',
            index=models.Index(fields=['deliverable_type'], name='api_service_deliver_a42f78_idx'),
        ),
        migrations.RemoveField(
            model_name='scopeofworkitem',
            name='client',
        ),
        migrations.RemoveField(
            model_name='scopeofworkitem',
            name='scope_of_work',
        ),
        migrations.DeleteModel(
            name='ScopeOfWork',
        ),
        migrations.DeleteModel(
            name='ScopeOfWorkItem',
        ),
    ]
