# Generated by Django 6.0.3 on 2026-03-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_servicetaskdefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120)),
                ('task', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('deliverable_type', models.CharField(max_length=100)),
                ('monthly_limit', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('tracking_method', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client__name', 'service', 'task'],
            },
        ),
        migrations.RemoveIndex(
            model_name='servicetaskdefinition',
            name='api_service_service_e177a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicetaskdefinition',
            name='api_service_task_3324ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicetaskdefinition',
            name='api_service_deliver_a42f78_idx',
        ),
        migrations.DeleteModel(
            name='ServiceTaskDefinition',
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_of_work_items', to='api.client'),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['client'], name='api_scopeof_client__59772f_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['service'], name='api_scopeof_service_c9e84e_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['task'], name='api_scopeof_task_3b249c_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['deliverable_type'], name='api_scopeof_deliver_61a3d8_idx'),
        ),
    ]
