# Generated by Django 6.0.3 on 2026-03-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_task_to_deliverable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scopeofwork',
            new_name='api_scopeof_deliver_edffb4_idx',
            old_name='api_scopeof_deliverable_idx',
        ),
    ]
