# Generated by Django 6.0.3 on 2026-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_api_scopeof_deliverable_idx_api_scopeof_deliver_edffb4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeofwork',
            name='deliverable_type',
            field=models.CharField(choices=[('Creative', 'Creative'), ('Video', 'Video'), ('Copy', 'Copy'), ('Content Calendar', 'Content Calendar'), ('Campaign Setup', 'Campaign Setup'), ('Campaign Optimization', 'Campaign Optimization'), ('Report', 'Report'), ('Social Media Post', 'Social Media Post'), ('Reel / Short Video', 'Reel / Short Video'), ('Ad Creative', 'Ad Creative'), ('Landing Page', 'Landing Page'), ('Website Update', 'Website Update'), ('SEO Optimization', 'SEO Optimization'), ('Email Campaign', 'Email Campaign'), ('Marketing Collateral', 'Marketing Collateral'), ('Campaign', 'Campaign'), ('Optimization', 'Optimization'), ('Research', 'Research'), ('Strategy', 'Strategy'), ('Page', 'Page'), ('Meeting / Consultation', 'Meeting / Consultation')], max_length=100),
        ),
    ]
