# Generated by Django 6.0.3 on 2026-03-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_scopeofwork_deliverable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_interface_contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
