# Generated by Django 6.0.3 on 2026-03-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_client_client_interface_contact_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='api_client_brand_n_25e2c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='api_client_designa_cde923_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='designated_person',
        ),
    ]
