# Generated by Django 6.0.3 on 2026-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_client_api_client_brand_n_25e2c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeofwork',
            name='deliverable_type',
            field=models.CharField(choices=[('Website Development', 'Website Development'), ('Social Media Management', 'Social Media Management'), ('SEO', 'SEO'), ('Performance Marketing', 'Performance Marketing'), ('Brand Logo', 'Brand Logo'), ('Brand Guide', 'Brand Guide'), ('Brand Collateral', 'Brand Collateral')], max_length=100),
        ),
    ]
