# Generated by Django 6.0.3 on 2026-03-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_scopeofwork_deliverable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeofwork',
            name='service',
            field=models.CharField(choices=[('Website Development', 'Website Development'), ('Social Media Management', 'Social Media Management'), ('SEO', 'SEO'), ('Performance Marketing', 'Performance Marketing'), ('Brand Logo', 'Brand Logo'), ('Brand Guide', 'Brand Guide'), ('Brand Collateral', 'Brand Collateral')], max_length=120),
        ),
    ]
