# Generated by Django 6.0.3 on 2026-03-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_scopeofwork_service_multiselect'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scopeofwork',
            name='api_scopeof_deliver_61a3d8_idx',
        ),
        migrations.RemoveField(
            model_name='scopeofwork',
            name='deliverable_type',
        ),
        migrations.RemoveField(
            model_name='scopeofwork',
            name='tracking_method',
        ),
        migrations.RemoveField(
            model_name='scopeofwork',
            name='unit',
        ),
    ]
