# Generated by Django 6.0.3 on 2026-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_scopeofwork_api_scopeof_deliver_61a3d8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scopeofwork',
            name='api_scopeof_service_c9e84e_idx',
        ),
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='service',
            new_name='service_category',
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['service_category'], name='api_scopeof_service_7ec19f_idx'),
        ),
        migrations.AlterModelOptions(
            name='scopeofwork',
            options={'ordering': ['client__name', 'service_category', 'deliverable']},
        ),
    ]
