# Generated by Django 6.0.3 on 2026-03-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_scopeofwork_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='monthly_limit',
            new_name='monthly_unit',
        ),
    ]
