# Generated by Django 6.0.3 on 2026-03-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_scopeofwork_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopeofwork',
            options={'ordering': ['client__name', 'service_category']},
        ),
        migrations.RemoveIndex(
            model_name='scopeofwork',
            name='api_scopeof_deliver_edffb4_idx',
        ),
        migrations.RemoveField(
            model_name='scopeofwork',
            name='deliverable',
        ),
    ]
