# Generated by Django 6.0.3 on 2026-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_scopeofwork_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeofwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
