# Generated by Django 6.0.3 on 2026-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_scopeofwork_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopeofwork',
            options={'ordering': ['client__name', 'service_category', 'deliverable_name']},
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='deliverable_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['deliverable_name'], name='api_scopeof_deliver_8770a4_idx'),
        ),
    ]
