# Generated by Django 6.0.3 on 2026-03-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_scopeofwork_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='api_task_brand_i_5cbf40_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.client'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['client'], name='api_task_client__cca7f2_idx'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='brand',
        ),
    ]
