# Generated by Django 6.0.3 on 2026-03-13 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_task_api_task_brand_i_5cbf40_idx_task_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'client__name'],
                'indexes': [models.Index(fields=['user'], name='api_cliento_user_id_71cbaf_idx'), models.Index(fields=['client'], name='api_cliento_client__481c17_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client'), name='uniq_client_owner_user_client')],
            },
        ),
    ]
