# Generated by Django 6.0.3 on 2026-03-13 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_clientowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['target_date'], name='api_task_target__bfa97d_idx'),
        ),
    ]
