# Generated by Django 6.0.3 on 2026-03-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_task_target_date_task_api_task_target__bfa97d_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-target_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='api_task_given_a_53ba26_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='given_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submitted_at',
        ),
    ]
