# Generated by Django 6.0.3 on 2026-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_task_redo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type_name', models.CharField(max_length=255, unique=True)),
                ('point', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['work_type_name'],
                'indexes': [models.Index(fields=['work_type_name'], name='api_typeofw_work_ty_3a2a60_idx')],
            },
        ),
    ]
