# Generated by Django 6.0.3 on 2026-03-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_typeofwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.typeofwork'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['type_of_work'], name='api_task_type_of_952d3f_idx'),
        ),
    ]
