# Generated by Django 6.0.3 on 2026-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_task_type_of_work_task_api_task_type_of_952d3f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofwork',
            name='point',
            field=models.FloatField(default=0.0),
        ),
    ]
