# Generated by Django 6.0.3 on 2026-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_typeofwork_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='InstructionsByArtDirector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
