# Generated by Django 6.0.3 on 2026-03-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_task_excellence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_service_name_27d088_idx')],
            },
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_of_work', to='api.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='typeofwork',
            index=models.Index(fields=['service_category'], name='api_typeofw_service_ecc9f6_idx'),
        ),
    ]
