# Generated by Django 6.0.3 on 2026-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_servicecategory_typeofwork_service_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='monthly_unit',
            new_name='total_unit',
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
