# Generated by Django 6.0.3 on 2026-03-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_scopeofwork_service_category_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scopeofwork',
            new_name='api_scopeof_service_7c5d8c_idx',
            old_name='api_scopeof_service_8ccda8_idx',
        ),
    ]
