# Generated by Django 6.0.3 on 2026-03-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_negativeremark'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='negativeremark',
            new_name='api_negativ_task_id_c9d2c4_idx',
            old_name='api_negativ_task_id_7f7dc0_idx',
        ),
        migrations.RenameIndex(
            model_name='negativeremark',
            new_name='api_negativ_remark__374d01_idx',
            old_name='api_negativ_remark__2b7d3c_idx',
        ),
        migrations.RenameIndex(
            model_name='negativeremark',
            new_name='api_negativ_point_f41042_idx',
            old_name='api_negativ_point_6b20ff_idx',
        ),
    ]
