# Generated by Django 6.0.3 on 2026-03-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_task_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='negativeremarkontask',
            new_name='api_negativ_task_id_4d7be0_idx',
            old_name='api_negativ_task_id_2b1f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='negativeremarkontask',
            new_name='api_negativ_negativ_828c77_idx',
            old_name='api_negativ_negativ_0e76b1_idx',
        ),
    ]
