# Generated by Django 6.0.3 on 2026-03-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_taskattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskattachment',
            new_name='api_taskatt_task_id_142d80_idx',
            old_name='api_taskatt_task_id_a98fe0_idx',
        ),
        migrations.RenameIndex(
            model_name='taskattachment',
            new_name='api_taskatt_created_c2d1df_idx',
            old_name='api_taskatt_created_85faaa_idx',
        ),
    ]
