# Generated by Django 6.0.3 on 2026-03-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_clientattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientattachment',
            new_name='api_clienta_client__045cb3_idx',
            old_name='api_clienta_client__8def06_idx',
        ),
        migrations.RenameIndex(
            model_name='clientattachment',
            new_name='api_clienta_created_3e1bef_idx',
            old_name='api_clienta_created_69dcec_idx',
        ),
    ]
