# Generated by Django 6.0.3 on 2026-03-23 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_scopeofwork_type_of_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scope_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.scopeofwork'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scope_of_work'], name='api_task_scope_o_013300_idx'),
        ),
    ]
