# Generated by Django 6.0.3 on 2026-03-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_task_scope_of_work_task_api_task_scope_o_013300_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='typeofwork',
            name='api_typeofw_service_ecc9f6_idx',
        ),
        migrations.RemoveField(
            model_name='typeofwork',
            name='service_category',
        ),
    ]
