# Generated by Django 6.0.3 on 2026-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_typeofwork_api_typeofw_service_ecc9f6_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scopeofwork',
            constraint=models.UniqueConstraint(fields=('client', 'service_category'), name='uniq_scope_of_work_client_service_category'),
        ),
    ]
