# Generated by Django 6.0.3 on 2026-03-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_scopeofwork_uniq_scope_of_work_client_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
    ]
