# Generated by Django 6.0.3 on 2026-03-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_task_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.typeofwork'),
        ),
    ]
