# Generated by Django 6.0.3 on 2026-03-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_task_type_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='revision_type',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='', max_length=10),
        ),
    ]
