# Generated by Django 6.0.3 on 2026-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_group_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofwork',
            name='major_changes_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='minor_changes_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='redo_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='slides',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
