# Generated by Django 6.0.3 on 2026-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_typeofwork_major_changes_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='have_major_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='have_minor_changes',
            field=models.BooleanField(default=False),
        ),
    ]
