# Generated by Django 6.0.3 on 2026-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_task_have_major_changes_task_have_minor_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slides',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
