# Generated by Django 6.0.3 on 2026-03-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_task_slides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofwork',
            name='slides',
        ),
    ]
