# Generated by Django 6.0.3 on 2026-03-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_typeofwork_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofwork',
            name='major_changes_point',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='minor_changes_point',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='redo_point',
            field=models.FloatField(default=1.0),
        ),
    ]
