# Generated by Django 6.0.3 on 2026-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_typeofwork_major_changes_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='excellence_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
