# Generated by Django 6.0.3 on 2026-03-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_task_excellence_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMonthlyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_amounts', to='api.client')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['client'], name='api_clientm_client__e99f1d_idx'), models.Index(fields=['date'], name='api_clientm_date_540139_idx')],
            },
        ),
    ]
