# Generated by Django 6.0.3 on 2026-03-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_clientmonthlyamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_tasksta_name_6652e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskOnStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_links', to='api.task')),
                ('task_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='api.taskstage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['task_stage'], name='api_taskons_task_st_58c28e_idx'), models.Index(fields=['task'], name='api_taskons_task_id_fc73d2_idx')],
            },
        ),
    ]
