# Generated by Django 6.0.3 on 2026-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_taskstage_taskonstage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskonstage',
            constraint=models.UniqueConstraint(fields=('task',), name='uniq_task_on_stage_task'),
        ),
    ]
