# Generated by Django 6.0.3 on 2026-03-27 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_taskonstage_uniq_task_on_stage_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('on_going', 'On Going'), ('approved', 'Approved')], default='backlog', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['stage'], name='api_task_stage_7ab497_idx'),
        ),
    ]
