# Generated by Django 6.0.3 on 2026-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_task_stage_task_api_task_stage_7ab497_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='monthly_post_impression',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
