# Generated by Django 6.0.3 on 2026-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_task_platform'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='api_task_platfor_002db2_idx',
            old_name='api_task_platform_4eccde_idx',
        ),
    ]
