# Generated by Django 6.0.3 on 2026-04-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_additionalpoints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='additionalpoints',
            new_name='api_additio_user_id_4e9f4f_idx',
            old_name='api_additio_user_id_f87e38_idx',
        ),
        migrations.RenameIndex(
            model_name='additionalpoints',
            new_name='api_additio_date_b7c163_idx',
            old_name='api_additio_date_3d7ea4_idx',
        ),
    ]
